import dotenv from "dotenv";

dotenv.config({ path: new URL("../../.env", import.meta.url) });

export const env = {
  NODE_ENV: process.env.NODE_ENV ?? "development",
  PORT: Number(process.env.PORT ?? 4000),
  FRONTEND_URL: process.env.FRONTEND_URL ?? "http://localhost:5173",
  CLERK_SECRET_KEY: process.env.CLERK_SECRET_KEY ?? "",
  DATABASE_URL: process.env.DATABASE_URL ?? "",
  SUPABASE_URL: process.env.SUPABASE_URL ?? "",
  SUPABASE_ANON_KEY: process.env.SUPABASE_ANON_KEY ?? "",
  SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY ?? "",
  STELLAR_NETWORK: process.env.STELLAR_NETWORK ?? "testnet",
  STELLAR_HORIZON_URL: process.env.STELLAR_HORIZON_URL ?? "https://horizon-testnet.stellar.org",
  STELLAR_SOURCE_PUBLIC_KEY: process.env.STELLAR_SOURCE_PUBLIC_KEY ?? "",
  STELLAR_SOURCE_SECRET_KEY: process.env.STELLAR_SOURCE_SECRET_KEY ?? "",
  STELLAR_EXPLORER_BASE_URL: process.env.STELLAR_EXPLORER_BASE_URL ?? "https://stellar.expert/explorer/testnet/tx",
  STELLAR_ANCHOR_BATCH_SIZE: Number(process.env.STELLAR_ANCHOR_BATCH_SIZE ?? 20),
  TRUSTLESS_WORK_MODE: process.env.TRUSTLESS_WORK_MODE ?? "mock",
  TRUSTLESS_WORK_KEY_ID: process.env.TRUSTLESS_WORK_KEY_ID ?? "",
  TRUSTLESS_WORK_API_KEY: process.env.TRUSTLESS_WORK_API_KEY ?? "",
  TRUSTLESS_WORK_BASE_URL: process.env.TRUSTLESS_WORK_BASE_URL ?? "https://dev.api.trustlesswork.com",
  TRUSTLESS_WORK_NETWORK: process.env.TRUSTLESS_WORK_NETWORK ?? "testnet",
  TRUSTLESS_WORK_SIGNER_PUBLIC_KEY: process.env.TRUSTLESS_WORK_SIGNER_PUBLIC_KEY ?? "",
  TRUSTLESS_WORK_SIGNER_SECRET_KEY: process.env.TRUSTLESS_WORK_SIGNER_SECRET_KEY ?? "",
  TRUSTLESS_WORK_APPROVER_PUBLIC_KEY: process.env.TRUSTLESS_WORK_APPROVER_PUBLIC_KEY ?? "",
  TRUSTLESS_WORK_PLATFORM_ADDRESS: process.env.TRUSTLESS_WORK_PLATFORM_ADDRESS ?? "",
  TRUSTLESS_WORK_RELEASE_SIGNER_PUBLIC_KEY: process.env.TRUSTLESS_WORK_RELEASE_SIGNER_PUBLIC_KEY ?? "",
  TRUSTLESS_WORK_DISPUTE_RESOLVER_PUBLIC_KEY: process.env.TRUSTLESS_WORK_DISPUTE_RESOLVER_PUBLIC_KEY ?? "",
  TRUSTLESS_WORK_USDC_ISSUER: process.env.TRUSTLESS_WORK_USDC_ISSUER ?? "",
  TRUSTLESS_WORK_PLATFORM_FEE: Number(process.env.TRUSTLESS_WORK_PLATFORM_FEE ?? 0),
};
